config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'books/new'
  root to: 'homes#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index', as: 'index_book'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end
  
  def index
    @book=Book.new
    @booka=Book.all
  end
  
  def create
    @book=Book.new(book_params)
    if @book.save
     flash[:notice]='Book was successfully created.'
     redirect_to book_path(@book.id)
    else
     @booka=Book.all
     render :index
    end
  end
  
   def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to '/books'
    flash[:notice]='Book was successfully destroyed'
  end
   
  def show
    @bookb=Book.find(params[:id])
  end

  def edit
    @bookb=Book.find(params[:id])
  end
  
  def update
     @bookb=Book.find(params[:id])
     if  @bookb.update(book_params)
      flash[:notice]='Book was successfully updated.'  
      redirect_to book_path(@bookb.id)
     else
      render :edit
     end
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class="edit-title">
 <h1>Editing Book</h1>
</div>

 <!--エラーを教えてくれるよ-->
<% if @bookb.errors.any? %>
<div class="edit-error">

  <div class="edit-error-text">
    <h6>
      <%= @bookb.errors.count %> errors prohibited this book from being saved:
    </h6>
  </div>
    
     <div class="edit-error-message">
     <% @bookb.errors.full_messages.each do |message| %>
        <ul>
        <li><%= message %></li>
        </ul>
     <% end %>
     </div>
    
    <div class="error-red-5">
    </div>
    <div class="error-red-6">
    </div>
    <div class="error-red-7">
    </div>
    <div class="error-red-8">
    </div>

</div>
<% end %>

<%= form_with model: @bookb, url: update_book_path(@bookb.id), method: :patch do |f| %>

<div class="edit-text-title">
    <h5>Title</h5>
 <%= f.text_field :title %>
</div>
 
<div class="edit-text-body">
    <h5>Body</h5>
 <%= f.text_field :body %> 
</div>

<div class="edit-ok">
   <%= f.submit 'Update Book' %>  
</div>

<% end %>

<div class="edit-jump-w">
　<%= link_to "Show", book_path, style: "color:black;" %><!--showへ-->
  <span>|</span>
  <%= link_to "Back", index_book_path, style: "color:black;" %>　<!--indexへ-->
</div>

app/views/books/index.html.erb
<div class="destroy-flash">
  <%= flash[:notice] %>
</div>

<div class="new-large">
  <h1>Books</h1>
</div>
　
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>

    
    <% @booka.each do |bookb| %>
    <tr>
     <td>
       <div class="test-me">
         <%= bookb.title %>
       </div>
     </td>
     <td>
       <div class"text-i">
          <%= bookb.body %>
       </div>
     </td>
     <td>
       <div class="show-jump">
         <%= link_to "Show", book_path(bookb.id), style: "color:black;" %>　<!--showへ-->
       </div>
     </td>
     <td>
       <div class="edit-jump">
          <%= link_to "Edit", edit_book_path(bookb.id), style: "color:black;" %>　<!--editへ-->
       </div>
     </td>
     <td>
       <div class="destroy">
          <%= link_to "Destroy", destroy_book_path(bookb.id), style: "color:black;", method: :delete, "data-confirm"=>"Are you sure?" %>
       </div>
     </td>
     
    </tr>
    <% end %>
    
  </tbody>
</table>

<div class="new-book">
  <h2>New Book</h2>
</div>

<!--エラーを教えてくれるよ-->
<% if @book.errors.any? %>
<div class="new-error">

  <div class="new-error-text">
    <h6>
      <%= @book.errors.count %> errors prohibited this book from being saved:
    </h6>
  </div>


    
     <div class="new-error-message">
     <% @book.errors.full_messages.each do |message| %>
        <ul>
        <li><%= message %></li>
        </ul>
     <% end %>
     </div>
    
    <div class="error-red-1">
    </div>
    <div class="error-red-2">
    </div>
    <div class="error-red-3">
    </div>
    <div class="error-red-4">
    </div>
  
  
</div>
<% end %>


<!--新しいフォーム-->


<%= form_with model: @book, method: :post do |f| %>
<div class="new-for-title">
  <p>Title</p>
  <%= f.text_field :title %>
</div>

<div class="new-for-body">
 <p>Body</p>
 <%= f.text_area :body %>
</div>

<div class="new-for-create">
 <p>
   <%= f.submit 'Create Book' %>
 </p>
</div>

<% end %>

app/views/books/show.html.erb
<div class="show-title">
  <h5><%= flash[:notice] %></h5>
</div>

<div class="show-deta-title">
  <h4>Title:</h4>
  <%= @bookb.title %>
</div>

<div class="show-data-body">
  <h4>Body:</h4>
  <%= @bookb.body %>
</div>

<div class="show-menu">
   <%= link_to "Edit", edit_book_path %><!--editへ-->
   <span>|</span>
   <%= link_to "Back", index_book_path %>　<!--indexへback-->
</div>

app/views/homes/top.html.erb
<div class="hello-title">
 <h1>ようこそ<strong>Bookers</strong>へ!</h1>
</div>

<div class="hello-text1">
  <strong>Bookers</strong><span> では、さまざまな書籍に関するあなたの意見や</span>
</div>

<div class="hello-text2">
  <p>印象を共有し交換することができます</p>
</div>
 
<div class="hello-start">
 <%= link_to "start", index_book_path %>  <!--indexへ遷移-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>